import { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    nav: {
      about: 'À propos',
      parcours: 'Parcours',
      projects: 'Projets',
      contact: 'Contact',
      cvBtn: 'CV',
      cvBtnFull: 'Télécharger mon CV',
    },
    hero: {
      available: 'Disponible pour des projets',
      role: 'Analyste & Développeur Web',
      location: 'Douala, Cameroun',
      description: 'Je transforme vos idées en produits digitaux percutants avec',
      contactBtn: 'Me contacter',
      cvBtn: 'Télécharger CV',
      terminalLines: [
        { cmd: 'whoami', output: 'happi-mathis' },
        { cmd: 'cat skills.json', output: '["Next.js", "React (Expo)", "Laravel", "Flutter"]' },
        { cmd: 'node --status', output: '✓ Disponible pour de nouveaux projets' },
        { cmd: 'git log --oneline -1', output: '🚀 feat: open to new collaborations' },
      ],
    },
    about: {
      sectionNum: '// 001',
      title: 'À propos de',
      titleHighlight: 'moi',
      whoTitle: 'Qui suis-je ?',
      whoP1: 'Basé à',
      whoP1Bold: 'Douala, Cameroun',
      whoP1Rest: ', je suis un développeur fullstack passionné par la création d\'applications web et mobiles qui simplifient la vie des utilisateurs et apportent une réelle valeur à mes clients.',
      whoP2Start: 'Avec une formation d\'ingénieur en informatique, je combine créativité et rigueur technique. Je maîtrise les',
      whoP2Bold: 'méthodes agiles',
      whoP2End: ': livraisons itératives, respect des délais et des budgets, communication continue à chaque étape du projet.',
      whoP3Start: 'Mon approche est',
      whoP3Bold: 'centrée sur le client',
      whoP3End: ': vous n\'êtes jamais laissé dans le flou. Je valide chaque étape avec vous et j\'ajuste rapidement si nécessaire.',
      locationLabel: 'Douala, Cameroun',
      languagesLabel: 'Français (natif) · Anglais (courant)',
      hobbiesLabel: 'Football · FIFA · COD · Tech',
      aiTitle: 'IA & Vibe Coding',
      aiText: 'Je maîtrise les derniers outils d\'IA pour accélérer le développement et garantir un code de qualité supérieure.',
      methodTitle: 'Méthode Agile',
      methodText: 'Livraisons itératives · Communication transparente · Adaptabilité aux changements · Respect des engagements.',
      methodItems: ['Respect des délais', 'Qualité de code', 'Communication continue'],
      skillsTitle: 'Compétences techniques',
      skills: [
        { title: 'Backend', tech: 'Laravel · PHP · Node.js' },
        { title: 'Mobile', tech: 'React Native (Expo) · Flutter · Dart' },
        { title: 'Frontend', tech: 'React · HTML · CSS · JS · Tailwind · Next.js' },
        { title: 'Bases de données', tech: 'MySQL · Firebase' },
        { title: 'Data Analysis', tech: 'R · R Shiny · ggplot2' },
        { title: 'Java', tech: 'POO · Spring Boot basics' },
        { title: 'Python', tech: 'Scripts · pandas · automatisation' },
        { title: 'Outils & Méthodes', tech: 'Git · Agile · Figma · VS Code' },
      ],
    },
    parcours: {
      sectionNum: '// 002',
      title: 'Mon',
      titleHighlight: 'Parcours',
      formationTitle: 'Formation',
      experienceTitle: 'Expérience',
      currentBadge: '● Actuel',
      education: [
        { degree: 'Master 1 — Génie Logiciel', school: 'Polytechnique', location: 'Douala', year: '2025 — 2026', tags: ['Génie Logiciel', 'Architecture', 'R&D'] },
        { degree: "Diplôme d'Ingénieur en Informatique", school: "Institut Africain d'Informatique (IAI)", location: 'Douala', year: '2021 — 2024', tags: ['Ingénierie', 'Systèmes', 'Réseaux'] },
        { degree: 'Licence en Informatique', school: "Institut Africain d'Informatique (IAI)", location: 'Douala', year: '2021 — 2024', tags: ['Développement', 'Algorithmique'] },
        { degree: 'Baccalauréat Série TI — Technique Informatique', school: 'Lycée Joss', location: 'Douala', year: '2021', tags: ['Informatique', 'Technique'] },
      ],
      experience: [
        {
          title: 'Analyste & Développeur Web',
          company: 'Awatechno',
          location: 'Douala',
          year: 'Nov. 2025 — Présent',
          current: true,
          tasks: [
            'Personnalisation et maintenance de sites WordPress premium',
            "Développement d'applications web avec Next.js",
            'Communication continue avec les clients à chaque étape',
            "Analyse des besoins, optimisation des interfaces et mise en production",
          ],
          tags: ['Next.js', 'WordPress', 'Agile'],
        },
        {
          title: 'Stagiaire Développeur',
          company: 'African Windows SARL',
          location: 'Douala',
          year: '2022',
          current: false,
          tasks: [
            "Conception d'une application web de gestion avec Laravel",
            'Optimisation des performances des bases de données MySQL',
            "Livraisons itératives et points réguliers avec l'équipe",
          ],
          tags: ['Laravel', 'PHP', 'MySQL'],
        },
        {
          title: 'Stagiaire IT',
          company: 'Mairie de Douala',
          location: 'Douala',
          year: '2021',
          current: false,
          tasks: ['Gestion de projets de numérisation', 'Support technique et formation des utilisateurs'],
          tags: ['IT', 'Formation', 'Numérique'],
        },
        {
          title: 'Stagiaire Mobile & Multimédia',
          company: 'CIJ',
          location: 'Douala',
          year: '2020',
          current: false,
          tasks: [
            "Développement d'une application mobile avec Flutter",
            'Création de montages vidéo et infographies pour campagnes numériques',
          ],
          tags: ['Flutter', 'Dart', 'Multimédia'],
        },
      ],
    },
    projects: {
      sectionNum: '// 003',
      title: 'Mes',
      titleHighlight: 'Réalisations',
      filterAll: 'Tous',
      viewDetails: 'Voir les détails →',
      visitProject: 'Visiter le projet',
      localProject: 'Projet local (non publié)',
      close: 'Fermer',
      data: [
        { id: 'almanac', title: 'Almanac Cameroun', summary: 'Application Laravel de gestion des villages et personnalités administratives au Cameroun.', description: "Cette application web a été développée pour centraliser et structurer les données administratives du Cameroun : villages, groupements et personnalités locales. Elle permet aux administrateurs et citoyens de rechercher facilement un village, visualiser les hiérarchies administratives et consulter les informations sur les chefs et groupements. L'apport principal : remplacer un système dispersé et papier par une plateforme digitale fiable, accessible et maintenable." },
        { id: 'laravel-voting', title: 'Laravel Voting Platform', summary: "Plateforme de vote en ligne sécurisée avec gestion de rôles, logs d'audit et nettoyage automatisé.", description: "Une plateforme de vote en ligne robuste et sécurisée. Elle gère les rôles (Administrateur/Votant) via Laravel Sanctum, propose une gestion avancée des scrutins avec des règles spécifiques (vote blanc, ex-aequo avec second tour automatique) et génère des Procès-Verbaux officiels en PDF. Un journal d'audit détaillé détecte et bloque les fraudes (double vote, vote hors délai). Enfin, des tâches cron automatisées assurent le nettoyage de la base de données après 24/48 heures." },
        { id: 'r-shiny', title: 'Dashboard R Shiny — Analyse', summary: "Dashboard interactif R Shiny pour analyser les habitudes d'utilisation des smartphones.", description: "Cette application interactive permet d'explorer et de visualiser les résultats du questionnaire NBMB sur l'utilisation des smartphones. Grâce à des graphiques dynamiques, des tableaux récapitulatifs et des filtres interactifs, les chercheurs peuvent identifier des tendances comportementales et extraire des insights stratégiques. L'outil transforme des données brutes en décisions éclairées. Déployé sur shinyapps.io." },
        { id: 'defgi', title: 'Site Vitrine — Defgi', summary: "Site vitrine WordPress pour améliorer la visibilité en ligne de Defgi.", description: "Réalisation d'un site vitrine WordPress professionnel pour Defgi afin d'accroître leur visibilité sur internet. Le site présente clairement leurs activités, leurs valeurs et leurs contacts avec un design responsive. Des optimisations SEO de base ont été intégrées pour améliorer le référencement naturel. Outils utilisés : WordPress, Elementor, Yoast SEO." },
        { id: 'awatechno', title: 'Site Vitrine — Awatechno', summary: "Site vitrine WordPress pour renforcer la présence digitale d'Awatechno.", description: "Développement du site vitrine WordPress pour Awatechno, une agence tech de Douala. L'objectif : leur donner une présence professionnelle sur le web pour se différencier de la concurrence et rassurer les clients potentiels. Le site présente leurs services avec une navigation claire, un design moderne adapté mobile et un temps de chargement optimisé." },
      ],
    },
    contact: {
      sectionNum: '// 004',
      title: 'Contactez-',
      titleHighlight: 'moi',
      description: "Vous avez une idée de projet, une question ou simplement envie d'échanger ? Je suis à votre écoute. Répondons ensemble à vos besoins digitaux.",
      whatsappDirect: 'Chat direct sur WhatsApp',
      formTitle: 'Envoyer un message',
      nameLabel: 'Votre nom',
      namePlaceholder: 'Happi mathis',
      emailLabel: 'Votre email',
      emailPlaceholder: 'kenwayhappi@gmail.com',
      messageLabel: 'Message',
      messagePlaceholder: "Bonjour, j'aimerais vous parler d'un projet...",
      sendBtn: 'Envoyer via WhatsApp',
      sendingBtn: 'Ouverture de WhatsApp...',
      waMessage: (name, email, message) =>
        `Bonjour Happi Mathis,\n\nJe m'appelle ${name}\nEmail : ${email}\n\n${message}`,
    },
    footer: {
      rights: 'Tous droits réservés.',
      tagline: 'Conçu & développé avec passion depuis Douala 🇨🇲',
    },
  },

  en: {
    nav: {
      about: 'About',
      parcours: 'Journey',
      projects: 'Projects',
      contact: 'Contact',
      cvBtn: 'CV',
      cvBtnFull: 'Download my CV',
    },
    hero: {
      available: 'Available for projects',
      role: 'Analyst & Web Developer',
      location: 'Douala, Cameroon',
      description: 'I turn your ideas into impactful digital products with',
      contactBtn: 'Contact me',
      cvBtn: 'Download CV',
      terminalLines: [
        { cmd: 'whoami', output: 'happi-mathis' },
        { cmd: 'cat skills.json', output: '["Next.js", "React (Expo)", "Laravel", "Flutter"]' },
        { cmd: 'node --status', output: '✓ Available for new projects' },
        { cmd: 'git log --oneline -1', output: '🚀 feat: open to new collaborations' },
      ],
    },
    about: {
      sectionNum: '// 001',
      title: 'About',
      titleHighlight: 'me',
      whoTitle: 'Who am I?',
      whoP1: 'Based in',
      whoP1Bold: 'Douala, Cameroon',
      whoP1Rest: ', I am a fullstack developer passionate about building web and mobile applications that simplify users\' lives and bring real value to my clients.',
      whoP2Start: 'With a computer engineering degree, I combine creativity and technical rigor. I master',
      whoP2Bold: 'agile methodologies',
      whoP2End: ': iterative deliveries, meeting deadlines and budgets, continuous communication at every project stage.',
      whoP3Start: 'My approach is',
      whoP3Bold: 'client-centered',
      whoP3End: ': you are never left in the dark. I validate each step with you and adjust quickly when needed.',
      locationLabel: 'Douala, Cameroon',
      languagesLabel: 'French (native) · English (fluent)',
      hobbiesLabel: 'Football · FIFA · COD · Tech',
      aiTitle: 'AI & Vibe Coding',
      aiText: 'I master the latest AI tools to accelerate development and ensure superior code quality.',
      methodTitle: 'Agile Method',
      methodText: 'Iterative deliveries · Transparent communication · Adaptability to changes · Commitment to deadlines.',
      methodItems: ['Meeting deadlines', 'Code quality', 'Continuous communication'],
      skillsTitle: 'Technical Skills',
      skills: [
        { title: 'Backend', tech: 'Laravel · PHP · Node.js' },
        { title: 'Mobile', tech: 'React Native (Expo) · Flutter · Dart' },
        { title: 'Frontend', tech: 'React · HTML · CSS · JS · Tailwind · Next.js' },
        { title: 'Databases', tech: 'MySQL · Firebase' },
        { title: 'Data Analysis', tech: 'R · R Shiny · ggplot2' },
        { title: 'Java', tech: 'OOP · Spring Boot basics' },
        { title: 'Python', tech: 'Scripts · pandas · automation' },
        { title: 'Tools & Methods', tech: 'Git · Agile · Figma · VS Code' },
      ],
    },
    parcours: {
      sectionNum: '// 002',
      title: 'My',
      titleHighlight: 'Journey',
      formationTitle: 'Education',
      experienceTitle: 'Experience',
      currentBadge: '● Current',
      education: [
        { degree: "Master's 1 — Software Engineering", school: 'Polytechnique', location: 'Douala', year: '2025 — 2026', tags: ['Software Eng.', 'Architecture', 'R&D'] },
        { degree: "Computer Engineering Degree", school: "African Institute of Computer Science (IAI)", location: 'Douala', year: '2021 — 2024', tags: ['Engineering', 'Systems', 'Networks'] },
        { degree: "Bachelor's in Computer Science", school: "African Institute of Computer Science (IAI)", location: 'Douala', year: '2021 — 2024', tags: ['Development', 'Algorithms'] },
        { degree: 'Baccalauréat — IT Technical Series (TI)', school: 'Lycée Joss', location: 'Douala', year: '2021', tags: ['IT', 'Technical'] },
      ],
      experience: [
        {
          title: 'Web Analyst & Developer',
          company: 'Awatechno',
          location: 'Douala',
          year: 'Nov. 2025 — Present',
          current: true,
          tasks: [
            'Customization and maintenance of premium WordPress sites',
            'Web application development with Next.js',
            'Continuous client communication at every stage',
            'Requirements analysis, interface optimization and deployment',
          ],
          tags: ['Next.js', 'WordPress', 'Agile'],
        },
        {
          title: 'Developer Intern',
          company: 'African Windows SARL',
          location: 'Douala',
          year: '2022',
          current: false,
          tasks: [
            'Design of a Laravel-based management web application',
            'MySQL database performance optimization',
            'Iterative deliveries and regular team check-ins',
          ],
          tags: ['Laravel', 'PHP', 'MySQL'],
        },
        {
          title: 'IT Intern',
          company: 'Mairie de Douala',
          location: 'Douala',
          year: '2021',
          current: false,
          tasks: ['Digitization project management', 'Technical support and user training'],
          tags: ['IT', 'Training', 'Digital'],
        },
        {
          title: 'Mobile & Multimedia Intern',
          company: 'CIJ',
          location: 'Douala',
          year: '2020',
          current: false,
          tasks: [
            'Mobile application development with Flutter',
            'Video editing and infographics for digital campaigns',
          ],
          tags: ['Flutter', 'Dart', 'Multimedia'],
        },
      ],
    },
    projects: {
      sectionNum: '// 003',
      title: 'My',
      titleHighlight: 'Projects',
      filterAll: 'All',
      viewDetails: 'View details →',
      visitProject: 'Visit project',
      localProject: 'Local project (unpublished)',
      close: 'Close',
      data: [
        { id: 'almanac', title: 'Almanac Cameroun', summary: 'Laravel application for managing villages and administrative figures in Cameroon.', description: "This web application was built to centralize and structure Cameroon's administrative data: villages, groupings and local figures. It allows administrators and citizens to easily search for a village, view administrative hierarchies and access information on chiefs and groupings. The key contribution: replacing a scattered paper-based system with a reliable, accessible and maintainable digital platform." },
        { id: 'laravel-voting', title: 'Laravel Voting Platform', summary: 'Secure online voting platform with role management, audit logs and automated cleanup.', description: "A robust and secure online voting platform. It manages roles (Admin/Voter) via Laravel Sanctum, offers advanced ballot management with specific rules (blank vote, tie-breakers with automatic runoffs) and generates official certified PDF minutes. A detailed audit log detects and blocks fraud (double voting, out-of-time voting). Automated cron tasks handle database cleanup after 24/48 hours." },
        { id: 'r-shiny', title: 'R Shiny Dashboard — Analysis', summary: 'Interactive R Shiny dashboard to analyze smartphone usage habits.', description: "This interactive application allows exploring and visualizing the results of the NBMB questionnaire on smartphone usage. Through dynamic charts, summary tables and interactive filters, researchers can identify behavioral trends and extract strategic insights. The tool transforms raw data into informed decisions. Deployed on shinyapps.io." },
        { id: 'defgi', title: 'Showcase Site — Defgi', summary: "WordPress showcase site to improve Defgi's online visibility.", description: "Creation of a professional WordPress showcase site for Defgi to increase their internet visibility. The site clearly presents their activities, values and contacts with a responsive design. Basic SEO optimizations were integrated to improve organic search rankings. Tools used: WordPress, Elementor, Yoast SEO." },
        { id: 'awatechno', title: 'Showcase Site — Awatechno', summary: "WordPress showcase site to strengthen Awatechno's digital presence.", description: "Development of the WordPress showcase site for Awatechno, a tech agency in Douala. The goal: give them a professional web presence to stand out from competitors and reassure potential clients. The site presents their services with clear navigation, a modern mobile-friendly design and optimized load times." },
      ],
    },
    contact: {
      sectionNum: '// 004',
      title: 'Contact',
      titleHighlight: 'me',
      description: "Do you have a project idea, a question or just want to chat? I'm here for you. Let's tackle your digital needs together.",
      whatsappDirect: 'Direct chat on WhatsApp',
      formTitle: 'Send a message',
      nameLabel: 'Your name',
      namePlaceholder: 'Happi mathis',
      emailLabel: 'Your email',
      emailPlaceholder: 'kenwayhappi@gmail.com',
      messageLabel: 'Message',
      messagePlaceholder: "Hello, I'd like to discuss a project with you...",
      sendBtn: 'Send via WhatsApp',
      sendingBtn: 'Opening WhatsApp...',
      waMessage: (name, email, message) =>
        `Hello Happi Mathis,\n\nMy name is ${name}\nEmail: ${email}\n\n${message}`,
    },
    footer: {
      rights: 'All rights reserved.',
      tagline: 'Designed & built with passion from Douala 🇨🇲',
    },
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('fr');
  const t = translations[lang];
  const toggleLang = () => setLang((l) => (l === 'fr' ? 'en' : 'fr'));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
